use resonant_collinearity::*;
use utility::test_case_n;

test_case_n!(example,
"
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
",
    part1: (part1::solve, 14),
    part2: (part2::solve, 0)
);